#!/bin/bash

THEME=${1:-"dark"}

rofi -modi "pdf:~/.config/rofi/modules/bib/open_pdf,md:~/.config/rofi/modules/bib/open_md,inbox:~/.config/rofi/modules/bib/open_inbox,clipboard:~/.config/rofi/modules/bib/clipboard" -show pdf -i -p " " -theme "$THEME" -sidebar-mode 
